// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VatDesk.Infrastructure.Persistence;

#nullable disable

namespace VatDesk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VatDeskDbContext))]
    [Migration("20260721115502_AddUserDisplayName")]
    partial class AddUserDisplayName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VatDesk.Infrastructure.Persistence.Entities.DeclarationCategoryTotalEntity", b =>
                {
                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_id");

                    b.Property<string>("VatCode")
                        .HasColumnType("text")
                        .HasColumnName("vat_code");

                    b.Property<string>("Direction")
                        .HasColumnType("text")
                        .HasColumnName("direction");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<decimal>("TotalGross")
                        .HasColumnType("numeric")
                        .HasColumnName("total_gross");

                    b.Property<decimal>("TotalNet")
                        .HasColumnType("numeric")
                        .HasColumnName("total_net");

                    b.Property<decimal>("TotalVat")
                        .HasColumnType("numeric")
                        .HasColumnName("total_vat");

                    b.HasKey("DeclarationId", "VatCode", "Direction");

                    b.ToTable("declaration_category_totals", (string)null);
                });

            modelBuilder.Entity("VatDesk.Infrastructure.Persistence.Entities.DeclarationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("integer")
                        .HasColumnName("error_rows");

                    b.Property<decimal>("NetVatPayable")
                        .HasColumnType("numeric")
                        .HasColumnName("net_vat_payable");

                    b.Property<string>("SourceFilename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_filename");

                    b.Property<string>("SourceFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_format");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalInputVat")
                        .HasColumnType("numeric")
                        .HasColumnName("total_input_vat");

                    b.Property<decimal>("TotalOutputVat")
                        .HasColumnType("numeric")
                        .HasColumnName("total_output_vat");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("ValidRows")
                        .HasColumnType("integer")
                        .HasColumnName("valid_rows");

                    b.Property<int>("WarningRows")
                        .HasColumnType("integer")
                        .HasColumnName("warning_rows");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("declarations", (string)null);
                });

            modelBuilder.Entity("VatDesk.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VatDesk.Infrastructure.Persistence.Entities.ValidationIssueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DeclarationId")
                        .HasColumnType("uuid")
                        .HasColumnName("declaration_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.ToTable("validation_issues", (string)null);
                });

            modelBuilder.Entity("VatDesk.Infrastructure.Persistence.Entities.DeclarationCategoryTotalEntity", b =>
                {
                    b.HasOne("VatDesk.Infrastructure.Persistence.Entities.DeclarationEntity", "Declaration")
                        .WithMany("CategoryTotals")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("VatDesk.Infrastructure.Persistence.Entities.DeclarationEntity", b =>
                {
                    b.HasOne("VatDesk.Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("VatDesk.Infrastructure.Persistence.Entities.ValidationIssueEntity", b =>
                {
                    b.HasOne("VatDesk.Infrastructure.Persistence.Entities.DeclarationEntity", "Declaration")
                        .WithMany("ValidationIssues")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("VatDesk.Infrastructure.Persistence.Entities.DeclarationEntity", b =>
                {
                    b.Navigation("CategoryTotals");

                    b.Navigation("ValidationIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
